# Generated by Django 2.2.4 on 2022-06-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='descriaption',
            new_name='description',
        ),
    ]
