# Generated by Django 2.2.4 on 2022-06-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20220619_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='desc',
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='courses_app.Courses')),
            ],
        ),
    ]
