# Generated by Django 2.2.4 on 2022-06-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20220619_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='courses_app.Courses'),
        ),
    ]
