# Generated by Django 2.2.4 on 2022-06-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='description',
            new_name='desc',
        ),
    ]
