# Generated by Django 2.2.4 on 2022-06-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='messages',
        ),
    ]
